library(shiny)
library(httr)
library(stringr)
library(shinyWidgets)
library(shinydashboard)
library("shinyjs")
library(chatgpt)
library("mathjaxr")
library(tools)
library(readr)
library(ggplot2)
library(readxl)
library("pastecs")
library(e1071)
library(tseries)
library(plotly)
library(bslib)
library(dplyr)
library(aTSA)
library(plm)
library(urca)
library(tsDyn)
library(tseries)
library(nnet)
library("mlogit")
library("stargazer")
library("marginaleffects")
library(MASS)
library(datasets)
library(vars)
library(mfx)
library(dynlm)
library("rugarch")
library(aTSA)
library(oglmx)
source("explain_stat.r")
source("explain_theory.r")
source("interpret_result.r")
source("interpret_result_stat.r")
source("ui.r")
source("server.r")
# required function 
Sys.setenv(OPENAI_API_KEY = "your own key")
api_key="your own key"
style1 <- "border: 1px solid #ddd; padding: 15px; margin-bottom: 15px; background-color: #f9f9f9;"

shinyApp(ui, server)
